name: Alerta a ntfy
on:
  push:
    branches:
      - main
jobs:
  notificar:
    runs-on: ubuntu-latest
    name: Hola mundo y notificacion
    steps:
      - name: Checkout del repo
        uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Ejecutar hola mundo
        run: node hello.js
      - name: Enviar notificacion a ntfy
        run: curl -H "Title: Nuevo push en hola-mundo" -d "Se subio codigo a main" https://ntfy.sh/devops-itla
